apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-8ndk
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-8ndk
    app.kubernetes.io/part-of: ci10t-776-0044-app
  name: devfile-sample-8ndk
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-8ndk
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-8ndk
    spec:
      containers:
      - image: quay.io/pmacik-testing/ci10t-776-0044-tenant/ci10t-776-0044-app/devfile-sample-8ndk@sha256:4142908a26d67d3251290e510e1aaa7fd51d031f6838258601025068d937c1bc
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
